version: "3.7"
services:
  ns-web-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../laravel/:/var/www/html/
    ports:
      - 8005:80
  ns-mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      - 3308:3306
  ns-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 5002:80

volumes:
  mysql-data:
